version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: http-proxy-middleware
    versions:
    - 1.3.0
  - dependency-name: express-rate-limit
    versions:
    - 5.2.6
